Repository RefugeRestrooms/refugerestrooms, pull requests merged in 2018-10, with the labels that each got.

#501 Update font stack
  app/assets/stylesheets/sass/_variables.scss
Labels: Hacktoberfest, Ready for Review, enhancement

#508 Fix empty restrooms db during development
  setup/entry
Labels: Ready for Review, bug

#500 CONTRIBUTING.md: Instructions for all platforms
  CONTRIBUTING.md
Labels: Ready for Review

#499 New generic feature proposal issue template
  .github/ISSUE_TEMPLATE/generic-proposal-issue-template.md
Labels: Ready for Review

#504 Replace ruby base-image in Dockerfile with slimmer version
  Dockerfile
Labels: Hacktoberfest, Ready for Review, enhancement

#505 Rails 5.2
  Gemfile
  Gemfile.lock
  bin/bundle
  bin/setup
  bin/update
  config/application.rb
  config/boot.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/assets.rb
  config/initializers/content_security_policy.rb
  config/initializers/new_framework_defaults.rb
  config/initializers/new_framework_defaults_5_2.rb
  config/puma.rb
  config/storage.yml
  db/schema.rb
  spec/api/v1/restrooms_spec.rb
  spec/controllers/pages_controller_spec.rb
  spec/controllers/restrooms_controller_spec.rb
Labels: Hacktoberfest, Ready for Review, enhancement, packages

#510 _head.html.haml: Update Maps API version
  app/views/layouts/_head.html.haml
Labels: Ready for Review, enhancement

#519 Add Italian translation
  config/application.rb
  config/locales/it/about.it.yml
  config/locales/it/business_info.yml
  config/locales/it/contacts.it.yml
  config/locales/it/devise.it.yml
  config/locales/it/footer.it.yml
  config/locales/it/navigation.it.yml
  config/locales/it/restroom.it.yml
  config/locales/it/restrooms.it.yml
  config/locales/it/search.it.yml
  config/locales/it/signs.it.yml
  config/locales/it/simple_form.it.yml
  config/locales/it/splash.it.yml
  config/locales/it/text_msg.it.yml
Labels: Hacktoberfest, enhancement, translations

#521 Adds Brazilian Portuguese (pt-BR) translation
  app/views/restrooms/show.html.haml
  config/application.rb
  config/locales/pt-BR/about.pt-BR.yml
  config/locales/pt-BR/activerecord.pt-BR.yml
  config/locales/pt-BR/business_info.pt-BR.yml
  config/locales/pt-BR/contacts.pt-BR.yml
  config/locales/pt-BR/devise.pt-BR.yml
  config/locales/pt-BR/footer.pt-BR.yml
  config/locales/pt-BR/navigation.pt-BR.yml
  config/locales/pt-BR/pt-BR.yml
  config/locales/pt-BR/restroom.pt-BR.yml
  config/locales/pt-BR/restrooms.pt-BR.yml
  config/locales/pt-BR/search.pt-BR.yml
  config/locales/pt-BR/signs.pt-BR.yml
  config/locales/pt-BR/simple_form.pt-BR.yml
  config/locales/pt-BR/splash.pt-BR.yml
  config/locales/pt-BR/text_msg.pt-BR.yml
Labels: Hacktoberfest, Ready for Review, enhancement, translations

#513 Docker: Don't geocode the db seed entries
  app/models/restroom.rb
  setup/entry
Labels: Ready for Review, enhancement
