Repository RefugeRestrooms/refugerestrooms, pull requests merged in 2020-10, with the labels that each got.

#638 Keeping filters state on pagination
  app/controllers/restrooms_controller.rb
  app/javascript/packs/views/restrooms/restrooms.js
  app/views/restrooms/index.html.haml
Labels: Hacktoberfest, enhancement, in progress

#644 Add rubocop and resolve lint errors
  .rubocop.yml
  .travis.yml
  CONTRIBUTING.md
  Gemfile
  Gemfile.lock
  app/admin/admin_user.rb
  app/admin/dashboard.rb
  app/admin/restroom.rb
  app/controllers/api/docs_controller.rb
  app/controllers/api/v1/restrooms.rb
  app/controllers/application_controller.rb
  app/controllers/contacts_controller.rb
  app/controllers/restrooms_controller.rb
  app/helpers/recaptcha_helper.rb
  app/models/contact.rb
  app/models/rating_level.rb
  app/models/restroom.rb
  app/services/save_restroom.rb
  features/step_definitions/edit_steps.rb
  spec/api/v1/restrooms_spec.rb
  spec/controllers/pages_controller_spec.rb
  spec/controllers/restrooms_controller_spec.rb
  spec/factories/restrooms.rb
  spec/features/contacts_spec.rb
  spec/features/restrooms_spec.rb
  spec/models/rating_level_spec.rb
  spec/models/restroom_spec.rb
  spec/services/save_restroom_spec.rb
  spec/spec_helper.rb
  spec/support/factory_bot.rb
  spec/support/locations.rb
  spec/support/rspec.rb
Labels: Hacktoberfest, Ready for Review

#651 Applying ADA filters for the Map view of search.
  app/controllers/restrooms_controller.rb
  app/javascript/packs/views/restrooms/index.js
  app/views/restrooms/index.html.haml
Labels: Hacktoberfest, Ready for Review, enhancement

#649 Add a standard configuration to every contributor follow
  .editorconfig
Labels: Hacktoberfest, Ready for Review, developer-oriented

#647 Enhancement/i18n thread safe
  app/controllers/application_controller.rb
  spec/controllers/pages_controller_spec.rb
  spec/controllers/restrooms_controller_spec.rb
  spec/support/shared_examples/localized_request.rb
Labels: Hacktoberfest, Ready for Review

#641 Housekeeping/Upgrade: Puma
  Gemfile.lock
Labels: Hacktoberfest, Ready for Review, dependencies, packages
